apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: contour
  demo: kustomize-contour

namespace: contour-ac

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
