apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: contour
  demo: kustomize-contour

namespace: tanzu-packages

resources:
- contour-psp.yaml
- contour-package-install.yaml
