apiVersion: v1
kind: Namespace
metadata:
  name: tanzu-test-01
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-test-01-sa
  namespace: tanzu-test-01
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tanzu-test-01-role
  namespace: tanzu-test-01
rules:
- apiGroups: ["apps","extensions","policy"]
  resources: ["pods","deployments","podsecuritypolicies"]
  verbs: ["get","list","watch","create","update","patch","delete","use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tanzu-test-01-rolebinding
  namespace: tanzu-test-01
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tanzu-test-01-role
subjects:
- kind: ServiceAccount
  name: tanzu-test-01-sa
  namespace: tanzu-test-01
